name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "Run Luacheck"
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"
        annotate: warning

    - name: Package
      uses: BigWigsMods/packager@v2
      with:
        args: -d

    - name: "Archive"
      uses: "actions/upload-artifact@v3"
      if: success()
      with:
        name: clicked-ci
        path: ".release/*.zip"
