name: Package Release
on:
	push:
		branches:
			- master
		tags:
			- '*'
jobs:
	build:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v1
		- name: Package Retail
			run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
			env:
				CF_API_KEY: ${{ secrets.CF_API_KEY }}
				GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
		- name: Package Classic
			run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.5
			env:
				CF_API_KEY: ${{ secrets.CF_API_KEY }}
				GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
