name: Release
on:
  push:
    tags:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
    steps:
    - uses: actions/checkout@v1
    - name: "Run Luacheck"
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . --no-color -q
    - name: Package Retail
      uses: BigWigsMods/packager@master
    - name: "Archive Retail"
      uses: "actions/upload-artifact@v2"
      if: success()
      with:
        name: clicked-retail
        path: ".release/*.zip"
    - name: Package Classic
      uses: BigWigsMods/packager@master
      with:
        args: -g 1.13.5
    - name: "Archive Classic"
      uses: "actions/upload-artifact@v2"
      if: success()
      with:
        name: clicked-classic
        path: ".release/*-classic.zip"
